name: Github release (from main)

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/**
      - .gitignore
      - build.sh
      - build-aarch64.sh
      - build-jvm.sh
      - LICENSE
      - mvnw
      - mvnw.cmd
      - README.md
      - release.sh
      
#  pull_request:
#    branches:
#      - main
#    paths-ignore:
#      - .github/workflows/**

jobs:
  call-github-release:
#    environment: development
    uses: qiot-project/qiot-ubi-all-reusable-workflows/.github/workflows/app-github-release.yml@main
    # To pass named inputs to a called workflow, use the "with" keyword in a job.
    with:
      ACTOR: ${GITHUB_ACTOR}
    # Use the "secrets" keyword to pass named secrets.
    secrets:
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
      ORG_GITHUB_TOKEN: ${{ secrets.RELEASE_BUILD_PAT }}
    # Workflows that call reusable workflows in the same organization or enterprise
    #  can use the "inherit" keyword to implicitly pass the secrets.
      # secrets: inherit
